# build wall-util, then publish to glab releases
stages:
  - build
  - release

build:
  image: rust:latest
  stage: build
  script:
    - cargo build --release

  artifacts:
    name: "wall-util from $CI_COMMIT_REF_NAME"
    paths:
      - target/release/wall-util

  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH