[package]
name = "wall-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.197"
serde_derive = "1.0.197"
structopt = "0.3.26"
chrono = "0.4.35"